[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Townk/vim-autoclose'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'wlangstroth/vim-racket'
[[plugins]]
repo = 'scrooloose/syntastic.git'
[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
[[plugins]]
repo = 'iamcco/markdown-preview.vim'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
